services:
  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    mem_limit: 1g
    mem_reservation: 512m
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
