/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ConnectionsIndexImport } from './routes/connections/index'
import { Route as ConnectionsCallbackImport } from './routes/connections/callback'
import { Route as ConnectionsAddImport } from './routes/connections/add'
import { Route as ConnectionsEnergyConnectionImport } from './routes/connections/$energy-connection'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsIndexRoute = ConnectionsIndexImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsCallbackRoute = ConnectionsCallbackImport.update({
  id: '/connections/callback',
  path: '/connections/callback',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsAddRoute = ConnectionsAddImport.update({
  id: '/connections/add',
  path: '/connections/add',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsEnergyConnectionRoute =
  ConnectionsEnergyConnectionImport.update({
    id: '/connections/$energy-connection',
    path: '/connections/$energy-connection',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/connections/$energy-connection': {
      id: '/connections/$energy-connection'
      path: '/connections/$energy-connection'
      fullPath: '/connections/$energy-connection'
      preLoaderRoute: typeof ConnectionsEnergyConnectionImport
      parentRoute: typeof rootRoute
    }
    '/connections/add': {
      id: '/connections/add'
      path: '/connections/add'
      fullPath: '/connections/add'
      preLoaderRoute: typeof ConnectionsAddImport
      parentRoute: typeof rootRoute
    }
    '/connections/callback': {
      id: '/connections/callback'
      path: '/connections/callback'
      fullPath: '/connections/callback'
      preLoaderRoute: typeof ConnectionsCallbackImport
      parentRoute: typeof rootRoute
    }
    '/connections/': {
      id: '/connections/'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections/$energy-connection': typeof ConnectionsEnergyConnectionRoute
  '/connections/add': typeof ConnectionsAddRoute
  '/connections/callback': typeof ConnectionsCallbackRoute
  '/connections': typeof ConnectionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections/$energy-connection': typeof ConnectionsEnergyConnectionRoute
  '/connections/add': typeof ConnectionsAddRoute
  '/connections/callback': typeof ConnectionsCallbackRoute
  '/connections': typeof ConnectionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/connections/$energy-connection': typeof ConnectionsEnergyConnectionRoute
  '/connections/add': typeof ConnectionsAddRoute
  '/connections/callback': typeof ConnectionsCallbackRoute
  '/connections/': typeof ConnectionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections/$energy-connection'
    | '/connections/add'
    | '/connections/callback'
    | '/connections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections/$energy-connection'
    | '/connections/add'
    | '/connections/callback'
    | '/connections'
  id:
    | '__root__'
    | '/'
    | '/connections/$energy-connection'
    | '/connections/add'
    | '/connections/callback'
    | '/connections/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsEnergyConnectionRoute: typeof ConnectionsEnergyConnectionRoute
  ConnectionsAddRoute: typeof ConnectionsAddRoute
  ConnectionsCallbackRoute: typeof ConnectionsCallbackRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsEnergyConnectionRoute: ConnectionsEnergyConnectionRoute,
  ConnectionsAddRoute: ConnectionsAddRoute,
  ConnectionsCallbackRoute: ConnectionsCallbackRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/connections/$energy-connection",
        "/connections/add",
        "/connections/callback",
        "/connections/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/connections/$energy-connection": {
      "filePath": "connections/$energy-connection.tsx"
    },
    "/connections/add": {
      "filePath": "connections/add.tsx"
    },
    "/connections/callback": {
      "filePath": "connections/callback.tsx"
    },
    "/connections/": {
      "filePath": "connections/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
